import { TimelineItem } from './timeline-item';

export const TIMELINEITEM: TimelineItem[] = [
    {
        id: 11,
        name: 'Dokument',
        content: 'Lorem Ipsum',
        info: 'Dokument hinzugefügt',
        author: 'Lisa',
        avatar: 'avatar_f.png',
        keywords: null,
        created: new Date('2018-01-01 12:00:00'),
        modified: new Date('2018-01-01 12:00:00'),
    },
    {
        id: 12,
        name: 'Dokument 2',
        content: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.       Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpatUt wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.',
        info: 'Dokument hinzugefügt',
        author: 'Hans',
        avatar: 'avatar_m.png',
        keywords: null,
        created: new Date('2018-01-01 12:00:00'),
        modified: new Date('2018-01-01 12:00:00'),
    },
    {
        id: 13,
        name: 'Dokument 3',
        content: 'Lorem Ipsum Lorem Ipsum',
        info: 'Dokument hinzugefügt',
        author: 'Lisa',
        avatar: 'avatar_f.png',
        keywords: null,
        created: new Date('2018-01-01 12:00:00'),
        modified: new Date('2018-01-01 12:00:00'),
    },
    {
        id: 13,
        name: 'Dokument 3',
        content: 'Lorem Ipsum',
        info: 'Dokument hinzugefügt',
        author: 'Lisa',
        avatar: 'avatar_f.png',
        keywords: null,
        created: new Date('2018-01-01 12:00:00'),
        modified: new Date('2018-01-01 12:00:00'),
    },
    {
        id: 13,
        name: 'Dokument 3',
        content: 'Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum',
        info: 'Dokument hinzugefügt',
        author: 'Hans',
        avatar: 'avatar_m.png',
        keywords: null,
        created: new Date('2018-01-01 12:00:00'),
        modified: new Date('2018-01-01 12:00:00'),
    },
];

